version: '1.0'
models:
  - name: null
    description: null
    data_tests: null
    meta: 
      owner: analytics
    columns:
      - name: null
        data_type: null
        description: null
        data_tests: null
        meta:
          gdpr_tags: null
